version: '3'
services:
  frontend:
    image: theraapster/remote-frontend:latest
    ports:
    - "80:80"
    volumes:
    - ./frontend/nginx/:/etc/nginx/conf.d
    - ./frontend/code/:/usr/share/nginx/html
    container_name: remote-frontend
    depends_on:
    - api
    networks:
    - remote_nw
    restart: always
    environment:
      NGINX_HOST: jlr8-laptop.local.raaps.net
    command: sh -c "envsubst '\$$NGINX_HOST' < /usr/share/nginx/html/index.html.template > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
  api:
    image: theraapster/remote-api:latest
    volumes:
    - ./api/:/usr/src/app
    container_name: remote-api
    networks:
    - remote_nw
    restart: always
networks:
  remote_nw:
    driver: bridge